### ISSUE TITLE
Crashes on server start-up with latest version.

### ISSUE THREAD

**Issue by pokesmells** [Mlodziak00/Skeletal-Remains-Fabric#2]
27.05 21:24:03 [Server] main/ERROR Failed to start the minecraft server
27.05 21:24:03 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'skeletalremains'!
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/UnclampedModelPredicateProvider
27.05 21:24:03 [Server] INFO at net.lightglow.util.SkeletalModelPredicateProvider.registerBow(SkeletalModelPredicateProvider.java:14) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.lightglow.util.SkeletalModelPredicateProvider.registerSKModels(SkeletalModelPredicateProvider.java:10) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.lightglow.SkeletalRemains.onInitialize(SkeletalRemains.java:39) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO ... 7 more
27.05 21:24:03 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.client.item.UnclampedModelPredicateProvider
27.05 21:24:03 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
27.05 21:24:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
27.05 21:24:03 [Server] INFO at net.lightglow.util.SkeletalModelPredicateProvider.registerBow(SkeletalModelPredicateProvider.java:14) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.lightglow.util.SkeletalModelPredicateProvider.registerSKModels(SkeletalModelPredicateProvider.java:10) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.lightglow.SkeletalRemains.onInitialize(SkeletalRemains.java:39) ~[skeletalremains-1.3.0.jar:?]
27.05 21:24:03 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
27.05 21:24:03 [Server] INFO ... 7 more

**Comment by Mlodziak00** [comment]
Something seems to be up with the registerBow function, I'll look into it soon.

**Comment by Mlodziak00** [comment]
Managed to fix 2 issues,
1. The SkeletalModelPredicateProvider class was defined in the Main class, instead of Client class, so that's fixed.
2. Fixed my small issue with the bow's FOV.

The fixes are already out on Modrinth, still waiting for CurseForge approval.
