### ISSUE TITLE
Unintended Mob Farm

### ISSUE THREAD

**Issue by YumatanGames** [Mlodziak00/Skeletal-Remains-Fabric#7]
Hi. 

I really like this mod, but I think the way some skeletons are spawning, specifically the "deserted", need to be tweaked. I'll link a video I captured of what I'm talking about, but just by having some large structure in the air, making the ground slightly dark, is enough to make those literally rain down. Super easy to make a mob farm, but also skeletons shouldn't just spawn in mid air like that without a spawner I think... 

https://youtu.be/igC2uurUkj4

**Comment by cheicen** [comment]
Having similar issue. 

Only Deserters, but for me they're spawning in areas that should have enough light level and during the day.

**Comment by Mlodziak00** [comment]
I'll look into it, the way 1.20+ had changed code made mob spawning more confusing for me, I'll look into it right away.

**Comment by Mlodziak00** [comment]
Okay nvm, it was my error, I forgot to add in restrictions for spawning for the deserters, all of them have the:
```
SpawnRestriction.register(SKEntityType.SWAMPED_SKELETON - Type of skeleton
SpawnRestriction.Location.ON_GROUND, - If it should spawn on the ground, in water or in air
Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, - If there is anything above it that needs to spawn
HostileEntity::canSpawnInDark); - And if the entity should spawn in air
```
And I managed to forget that.
I'll be updating it shortly after I figure out an another issue with the Sunken Skeleton for Forge.
