### ISSUE TITLE
Keep crashing whenever any sunken spawn

### ISSUE THREAD

**Issue by SeppyBeep** [Mlodziak00/Skeletal-Remains-Fabric#8]
[crash-2023-07-02_01.58.18-server.txt](https://github.com/Mlodziak00/Skeletal-Remains-Fabric/files/11930142/crash-2023-07-02_01.58.18-server.txt)

**Comment by SeppyBeep** [comment]
I crash whenever any sunken appear, getting Ticking world from them trying to access private field

**Comment by Gbergz** [comment]
can confirm this crash

**Comment by DynamiteTy** [comment]
Can confirm this crash as well, even force spawned a Sunken with a spawn egg, causing an instant crash.

**Comment by Mlodziak00** [comment]
I've been trying to resolve this issue for a while now, yet to figure out the issue, might need to rewrite the entire Sunken Skeleton entity once I'm at my workspace

**Comment by SeppyBeep** [comment]
you could temporarily disable them or add a config that lets us choose what mobs can or cant spawn from the mod giving you time to fix it and allow people to enjoy the mod :D

**Comment by Mlodziak00** [comment]
The mod does have a config (forge only due to me not knowing any forge alternatives that work with JSON files), you can change the values of minimum and maximum spawn rates, and set them both to 0

**Comment by Gbergz** [comment]
Setting the config to 0 makes the crash still happen. I've tried it.

**Comment by Mlodziak00** [comment]
Yeah, forgot that it disables them from spawning, but the ones that already have spawned won't despawn.
I'd say temporarily disable the mod, so the skeleton that have currently spawned despawn, and re-enable it with the sunken min and max spawn config set to 0.
1 thing though, if you have the new items from the mod, it will get rid of them.

**Comment by Gbergz** [comment]
I meant as in a new world, with config values set to 0 makes the crash still happen.

**Comment by SeppyBeep** [comment]
what is the name of the config file? i cant find any name related to it in the folder

**Comment by Qee1y** [comment]
+1

**Comment by Mlodziak00** [comment]
The main reason for the crashes is, the way I've coded the sunken and the configs, sadly right now it's not possible to disable the sunken, due to it still registering them in the code.

I'll try my hardest to do this in my free time, but due to current circumstances, it's really difficult to work on my mods.

**Comment by Mlodziak00** [comment]
Pretty sure I managed to figure out the issue. I'll be rolling out the fix for Fabric today, Sadly Forge will have to wait.

**Comment by Qee1y** [comment]
Forge has Sinytra-connector mod
